#! /bin/sh

xsetroot -cursor_name left_ptr

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d   ﴣ    調   

bspc config border_width         2
bspc config window_gap          12


bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner 


bspc config focus_follows_pointer true
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config focused_border_color  "#0073a1"
bspc config normal_border_color   "#070530"

bspc rule -a qutebrowser desktop='^2'
bspc rule -a LibreWolf   desktop='^3'
bspc rule -a KeePassXC   desktop='^7'
bspc rule -a mpv	 desktop='^5'

exec open polybar       > /dev/null &
exec open qutebrowser   > /dev/null &
exec open librewolf     > /dev/null &
exec open keepassxc     > /dev/null &
exec open compton       > /dev/null &
exec open nm-applet     > /dev/null &
exec open light-locker  > /dev/null &
exec open unclutter     > /dev/null &
exec feh --bg-fill /usr/share/backgrounds/background.jpg
